steps:
  # Step 1: Install Node.js dependencies using the official Node.js 20 image
  # This image is pulled directly from Docker Hub.
  - name: "node:20"
    entrypoint: "npm"
    args: ["install"]
    id: "npm-install"

  # Step 2: Build the static site using the same official image
  - name: "node:20"
    entrypoint: "npm"
    args: ["run", "build"]
    id: "astro-build"
    waitFor: ["npm-install"]

  # Step 3: Deploy to Google Cloud Storage (no changes needed here)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "storage"
      - "rsync"
      - "--delete-unmatched-destination-objects" # <-- This is the correct flag
      - "dist/" # Sync the contents of the dist directory
      - "gs://${_BUCKET_NAME}"
    id: "deploy-to-gcs"
    waitFor: ["astro-build"]

  # Step 4: Invalidate CDN Cache (no changes needed here)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "compute"
      - "url-maps"
      - "invalidate-cdn-cache"
      - "${_URL_MAP_NAME}"
      - "--path=/*"
    id: "invalidate-cdn"
    waitFor: ["deploy-to-gcs"]

substitutions:
  _BUCKET_NAME: "astro-blog"
  # IMPORTANT: Make sure this value is your real URL map name
  _URL_MAP_NAME: "blog-lb"

options:
  logging: CLOUD_LOGGING_ONLY
