options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/blog-purge-key/versions/latest
      env: PURGE_KEY
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/blog-server:$COMMIT_SHA", "."]
    automapSubstitutions: true
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/blog-server:$COMMIT_SHA"]
    automapSubstitutions: true
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "blog-server"
      - "--image=gcr.io/$PROJECT_ID/blog-server:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
    secretEnv: ["PURGE_KEY"]
    automapSubstitutions: true
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        SERVICE_URL=$$(gcloud run services describe blog-server --platform=managed --region=us-central1 --format='value(status.url)')
        curl -X POST "$${SERVICE_URL}/purge-cache?key=$${PURGE_KEY}"
    secretEnv: ["PURGE_KEY"]
    automapSubstitutions: true
